version: 2

multi-ecosystem-groups:
  all:
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 10

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
    multi-ecosystem-group: "all"
  - package-ecosystem: "uv"
    directories:
      - "/"
    multi-ecosystem-group: "all"
  - package-ecosystem: "npm"
    directories:
      - "/"
    multi-ecosystem-group: "all"
