[project]
name = "bibra"
version = "0.1.0-dev"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.0",
    "fastapi==0.136.1",
    "pydantic-ai-slim[openai]>=1.93.0",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.28",
    "uvicorn==0.46.0",
    "pymupdf>=1.27.2",
    "pymupdf4llm>=1.27.2",
    "regex>=2026.5.9",
    "tiktoken>=0.12.0",
]

[project.scripts]
bibra = "bibra.cli:cli"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-asyncio>=1.0.0",
    "httpx>=0.28.0",
    "pytest-cov>=7.0.0",
    "ruff~=0.16.0",
    "pre-commit>=4.6.0",
    "schemathesis>=4.18.1",
    "bump-my-version>=1.3.0",
]

[build-system]
requires = ["uv_build>=0.11.15,<0.13"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "1 week"

[tool.uv.build-backend]
module-root = ""

[tool.ruff]
line-length = 88

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]

[tool.setuptools.packages.find]
include = ["bibra*"]

[tool.bumpversion]
current_version = "0.1.0-dev"
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:
        -                             # dash separator for pre-release section
        (?P<release>[a-zA-Z-]+)       # pre-release label
    )?                                # pre-release section is optional
"""
serialize = [
    "{major}.{minor}.{patch}-{release}",
    "{major}.{minor}.{patch}",
]
tag = true
sign_tags = true
commit = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[tool.bumpversion.parts.release]
values = ["dev", "prod"]
optional_value = "prod"
